# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'blank' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for blank
  pod 'EZAudio', '~> 1.1.4'

  target 'blankTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
